import type { ThisOrThatTask } from "./types";

export const thisOrThat1: ThisOrThatTask = {
  type: "thisorthat",
  series: "This or That",
  edition: 1,
  title: "Pokémon or Prescription?",
  blurb: "Is each name a Pokémon or a prescription drug brand?",
  buckets: ["Pokémon", "Drug"],
  items: [
    { label: "Absol", bucket: 0 },
    { label: "Abilify", bucket: 1, note: "Aripiprazole, an antipsychotic." },
    { label: "Zubat", bucket: 0 },
    { label: "Zoloft", bucket: 1, note: "Sertraline, an antidepressant." },
    { label: "Lunatone", bucket: 0 },
    { label: "Lunesta", bucket: 1, note: "Eszopiclone, a sleep aid." },
    { label: "Xatu", bucket: 0 },
    { label: "Xanax", bucket: 1, note: "Alprazolam, for anxiety." },
    { label: "Arbok", bucket: 0 },
    { label: "Ambien", bucket: 1, note: "Zolpidem, a sleep aid." },
    { label: "Seviper", bucket: 0 },
    { label: "Seroquel", bucket: 1, note: "Quetiapine, an antipsychotic." },
    { label: "Latuda", bucket: 1, note: "Lurasidone, an antipsychotic." },
    { label: "Lopunny", bucket: 0 },
    { label: "Klefki", bucket: 0 },
    { label: "Lyrica", bucket: 1, note: "Pregabalin, for nerve pain." },
    { label: "Otezla", bucket: 1, note: "Apremilast, for psoriasis." },
    { label: "Gligar", bucket: 0 },
    { label: "Farxiga", bucket: 1, note: "Dapagliflozin, for diabetes." },
    { label: "Dunsparce", bucket: 0 },
  ],
};

export const thisOrThat2: ThisOrThatTask = {
  type: "thisorthat",
  series: "This or That",
  edition: 2,
  title: "Typeface or Pasta?",
  blurb: "Is each name a typeface or a pasta shape?",
  buckets: ["Typeface", "Pasta"],
  items: [
    { label: "Garamond", bucket: 0 },
    { label: "Gemelli", bucket: 1, note: "Two strands twisted together." },
    { label: "Futura", bucket: 0 },
    { label: "Farfalle", bucket: 1, note: "Bow ties." },
    { label: "Calibri", bucket: 0 },
    { label: "Cavatappi", bucket: 1, note: "Corkscrew tubes." },
    { label: "Rockwell", bucket: 0 },
    { label: "Rotini", bucket: 1, note: "Short spirals." },
    { label: "Optima", bucket: 0 },
    { label: "Orecchiette", bucket: 1, note: "Little ears." },
    { label: "Trebuchet", bucket: 0 },
    { label: "Trofie", bucket: 1, note: "Short hand-rolled twists." },
    { label: "Bodoni", bucket: 0 },
    { label: "Bucatini", bucket: 1, note: "Thick spaghetti with a hole." },
    { label: "Cambria", bucket: 0 },
    { label: "Casarecce", bucket: 1, note: "Short rolled scrolls." },
    { label: "Perpetua", bucket: 0 },
    { label: "Strozzapreti", bucket: 1, note: "Priest-stranglers, hand-rolled." },
    { label: "Verdana", bucket: 0 },
    { label: "Mafaldine", bucket: 1, note: "Ribbons with wavy edges." },
  ],
};
